# {player} is the name of the dead player.
default: "{player} is dead."
void-death: "{player} fell into the void..."
fire-death: "{player} got burned..."
lava-death: "{player} can't swim in lava..."
water-death: "{player} can't swim..."
suicide-death: "{player} ended their own life..."
fall-death: "{player} didn't land on their feet..."
suffocation-death: "{player} stopped breathing..."
fire-tick-death: "{player} didn't put out the fire in time..."
projectile-death: "{player} isn't in the matrix..."
explosion-death: "{player} exploded..."
poison-death: "{player} didn't find the antidote..."
feed-death: "{player} died of hunger..."
falling-block-death: "{player} got something dropped on their head..."
