# Le {player} est remplacé par le nom du joueur mort.
void-death: "{player} est tombé dans le vide spacial ..."
fire-death: "{player} c'est brûlé les fesses ..."
lava-death: "{player} ne sait pas nager dans la lave ..."
water-death: "{player} ne sait pas nager ..."
suicide-death: "{player} à mis fin à ces jours ..."
fall-death: "{player} n'est pas retombé sur ces pieds ..."
suffocation-death: "{player} à arrêté de respirer ..."
fire-tick-death: "{player} n'a pas arreté le feu à temps ..."
projectile-death: "{player} n'est pas dans matrix ..."
explosion-death: "{player} c'est fait exploser ..."
poison-death: "{player} n'a pas trouver le remède ..."
feed-death: "{player} est mort de faim ..."
falling-block-death: "{player} à reçu quelque chose sur la tête ..."
